name: Lint

on: [pull_request]

jobs:
  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: './package.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
