name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push To Gitlab
        env: 
          token: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git config user.name "streamich"
          git config user.email "reactive-rpc@users.noreply.github.com"
          git remote add mirror "https://oauth2:${token}@gitlab.com/streamich/reactive-rpc.git"
          git push mirror master
